### ISSUE TITLE
Possible error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')

### ISSUE THREAD

**Issue by buley** [rubymotion/ib#90]
I had a functional WatchKit app, but after some unidentified environment changes (SDK update, Sierra) I cannot build and receive the following error:

The Gemfile is a simple case:

> source 'https://rubygems.org'
> 
> gem 'rake'
> gem 'ib'

Here's the relevant build output:

```

     Build watch_app/build/WatchOS-2.0-Release
   Compile ../../.rvm/gems/ruby-2.2.2/gems/ib-1.0.1/lib/ib/outlets.rb
   Compile watch_app/app/extension_delegate.rb
   Compile watch_app/app/glance_controller.rb
   Compile watch_app/app/session_delegate.rb
   Compile watch_app/app/interface_controller.rb
   Compile watch_app/app/notification_controller.rb
   Compile watch_app/app/row_controller.rb
error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')
error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')
error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')
error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')
error: Invalid record (Producer: 'LLVM3.8.0' Reader: 'LLVM 7.3.0')
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion/lib/motion/project/template/ios-extension-builder.rb:172:in `block (2 levels) in build'
/Library/RubyMotion/lib/motion/project/template/ios-extension-builder.rb:139:in `each'
/Library/RubyMotion/lib/motion/project/template/ios-extension-builder.rb:139:in `block in build'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `call'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `block (2 levels) in initialize'
Tasks: TOP => build:device
(See full trace by running task with --trace)
    ERROR! Target 'watch_app' failed to build

```

This is possibly user error, but I've crossposted at http://community.rubymotion.com/t/watchkit-built-error-invalid-record-producer-llvm3-8-0-reader-llvm-7-3-0/1861

**Comment by buley** [comment]
The relevant lines in `ios-extension-builder.rb` do not suggest this is an issue with `ib` gem. Probably an issue with Rubymotion. Closing. 

>               sh "#{cxx} -fexceptions -c -arch #{arch} \"#{asm}\" -o \"#{arch_obj}\" -fembed-bitcode -mwatchos-version-min=#{config.deployment_target}"
